### ISSUE TITLE
Switching Layouts

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#15]
- [ ] Make Mechanism such that if you have last opened the second layout then even after killing the app when you reopen the app it should directly open the second layout, same for the first layout.

Hint: make use of SplashSceen Activity

**Comment by dishantvyas15** [comment]
I'd like to solve this issue.

**Comment by HemangNakarani** [comment]
> I'd like to solve this issue.

Assigned !!

**Comment by dishantvyas15** [comment]
Have made a pull request. Please review it.

**Comment by HemangNakarani** [comment]
> Have made a pull request. Please review it.

Done. Please, check review on your PR.
