### ISSUE TITLE
Bottom Navigation in second layout.

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#16]
- [ ] Simply Just Add bottom navigation with 3 tabs in the second layout activity, it is not required to make it work fully functional.

**Comment by sanchi0204** [comment]
@HemangNakarani  I have made a PR for the previously assigned issue. Pls assign this

**Comment by sanchi0204** [comment]
Pls tell the required fields as I have to add icons and labels accordingly

**Comment by HemangNakarani** [comment]
We'll have 3 fields of contest types
Long, Short, Live

**Comment by sanchi0204** [comment]
pls assign me

**Comment by sanchi0204** [comment]
Do I need to add fragments or activities or leave it as it is?

**Comment by HemangNakarani** [comment]
No, you don't need to add fragments as of now.

**Comment by sanchi0204** [comment]
@HemangNakarani pls assign me the issue and review the PR
