### ISSUE TITLE
Make Utils>Constants.java file

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#24]
- [x] Make Constants.java file under the folder Utils.
- [x] Write Constant variables in it. They should be static.
- [x] Replace all occurrences of this constant variable in the project by this Constant Variables.

**Comment by ashishpatel16** [comment]
@HemangNakarani I'll do this one.

**Comment by HemangNakarani** [comment]
@ashishpatel16 Go ahed !!

**Comment by HemangNakarani** [comment]
@ashishpatel16  Any Updates on this issue?

**Comment by ashishpatel16** [comment]
Yeah, I just created a PR!

**Comment by HemangNakarani** [comment]
I have added comment.
https://github.com/prit29/Coders-Calendar/pull/39#pullrequestreview-502861078
