### ISSUE TITLE
Make Tablayout Dynamic

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#3]
User can add tab from tablayot, from settings for particular coding platforms

**Comment by ashishpatel16** [comment]
@HemangNakarani I'd like to make this.

**Comment by ashishpatel16** [comment]
I have a few confusions. 
* Basically what we need is based on the marked contests from setting activity, we will dynamically just display only that selected number of tabs. 
* The layout one and layout two both are supposed to have this same tab layout. 
* Layout one currently contains a linear layout with coders calendar, slop etc written. I'm supposed to replace that linear layout with view pager, if I'm not wrong.
Do let me know if I'm getting this task right.

**Comment by prit29** [comment]
- point one you got right, we need exact same functionality.
- You just need to make this thing in layout one. Don't do anything in layout 2.
- You don't need to add viewpager for now, just work with tabs, only selected tabs should be shown in Layout one.

For more details.
Link: https://play.google.com/store/apps/details?id=com.noobsever.codingcontests

**Comment by ashishpatel16** [comment]
Hey mentors! @HemangNakarani @prit29 
Here's what I've done so far :
* Removed all tab items from xml, made an intent that opens up Settings activity. (which seems laggy on my physical device)
* Although we can do many things, I assumed that somehow we receive a list of strings from settings activity with names of all tabs that were checked.
* Then I dynamically add them to layout. And by default if the settings act. isn't opened, we display all the tabs.

**Comment by ashishpatel16** [comment]
I'm still confused because there isn't clarity on how I'm going to receive which tabs to display. 😅
Do guide me, I'm making the PR soon. 👍

**Comment by HemangNakarani** [comment]
@ashishpatel16 see my comment on your PR.
