### ISSUE TITLE
Make ViewPager and and attach it with TabLayout

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#30]
- [x] For each contest platform we'll need one fragment. So accordingly make fragments also.
- [x] Make Viewpager and Attach it with Tab layout and Fragments.

**[Reference : tablayout and view pager](https://www.javatpoint.com/android-tablayout)**

**Comment by ashishpatel16** [comment]
Can I take this issue?

**Comment by HemangNakarani** [comment]
Sure, Go Ahead !!

**Comment by ashishpatel16** [comment]
@HemangNakarani Fragments are supposed to be blank for now, right?

**Comment by ashishpatel16** [comment]
@HemangNakarani @prit29  I have a suggestion, In settings as well as LayoutOneActivity we have snippets of redundant code like fetching the list of tab items from SharedPreferences and saving them back to SharedPreferences using Gson. 

I want to add methods for them in **Utils>Methods.java** class to make it look cleaner. Can I add them in the PR I'll make solving this issue #30 ?

I'll just add a public method that returns a list of strings in a **fetchTabItems( )** method and one void method for saving the list using **saveTabItems( )** method.

**Comment by HemangNakarani** [comment]
> @HemangNakarani @prit29 I have a suggestion, In settings as well as LayoutOneActivity we have snippets of redundant code like fetching the list of tab items from SharedPreferences and saving them back to SharedPreferences using Gson.
> 
> I want to add methods for them in **Utils>Methods.java** class to make it look cleaner. Can I add them in the PR I'll make solving this issue #30 ?
> 
> I'll just add a public method that returns a list of strings in a **fetchTabItems( )** method and one void method for saving the list using **saveTabItems( )** method.

Yeah, Very Nice idea. Go ahead. I have opened a separate issue for it. So you can make a new PR besides this issue.
@ashishpatel16 comment on #43 so I can assign it to you.

**Comment by ashishpatel16** [comment]
@HemangNakarani @prit29 I've made a PR #45 . Do Suggest Changes!
