### ISSUE TITLE
Make Toggle Buttons in Second Layout

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#31]
- [ ] Make 3 Toggle Buttons in Second Layout at the bottom of the activity - bottom navigation using a toggle button
- [ ] Attach 3 different Fragments with each button

![image](https://user-images.githubusercontent.com/45796208/95118501-0eba0f80-0768-11eb-9d74-020313494b0a.png)

###### Button contains icon & Selected button contains icon + text | You can create in your way
**[Reference : Toggle Button](https://material.io/develop/android/components/buttons#toggle-button)**

**Comment by dishantvyas15** [comment]
I'd like to work on this issue.

**Comment by HemangNakarani** [comment]
@dishantvyas15 I have assigned this issue to you. Now you can work on it.

**Comment by dishantvyas15** [comment]
@HemangNakarani Please provide me with the labels that I should put in the buttons and the fragments.

**Comment by HemangNakarani** [comment]
# Long Short Live 
These are 3 segments

**Comment by HemangNakarani** [comment]
@dishantvyas15 any updates ?

**Comment by dishantvyas15** [comment]
> @dishantvyas15 any updates ?
@HemangNakarani Re-started working on this. Will revert back soon.
