### ISSUE TITLE
Make Activities with Appbar

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#32]
## Make Following Activities with Appbar
- Notification Activity
- HelpActivity
- SuggestUsActivity

![image](https://user-images.githubusercontent.com/45796208/95119988-7b360e00-076a-11eb-898f-0536658f0b7e.png)
- Set Titles name as Activity Names
- Add BackButtons in Appbar

- [ ] Add App bar in SettingsActivity and LayoutTwoActivity

**Comment by ashishpatel16** [comment]
@HemangNakarani Can I take this issue?

**Comment by ashishpatel16** [comment]
Can you explain **back buttons in appbar**? Like Instead of the hamburger icon we need back button icon in the specified activitites?

**Comment by HemangNakarani** [comment]
Yupp !! Go goa gone. 😁

**Comment by ashishpatel16** [comment]
@HemangNakarani All of these activities should have app bar? 
And can you explain **BackButtons on App bar**?

**Comment by ashishpatel16** [comment]
This is how settings activity and Suggest Us activity look like after my changes, 
How is **back button** to be added here? 

<img src="https://user-images.githubusercontent.com/59373024/95823178-c774e580-0d4a-11eb-9544-b36299b4b61c.jpeg" height="650"> <img src="https://user-images.githubusercontent.com/59373024/95824498-060b9f80-0d4d-11eb-829f-94026ca678a8.jpeg" height="650">

**Comment by HemangNakarani** [comment]
@ashishpatel16  No, it should not exactly look like this, all activities other then `LayoutOneActivity` and `LayoutTwoActivity` **will not** have this hamburger icon, search icon and that stack icon. All other activities will have just back button icon and activity name.
