### ISSUE TITLE
Fix : Toogle button in Settings Activity

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#33]
- [ ] Fix toggling of 24-hours and 12 hours timezone, if one of then is enable then other should be disable

***Below Should not happen***

![image](https://user-images.githubusercontent.com/45796208/95120810-b8e76680-076b-11eb-972d-c08bd0bd2d5b.png)

**Comment by dishantvyas15** [comment]
I'd like to work on this issue.
Requesting assignment.

**Comment by fenu28** [comment]
@dishantvyas15 As you have been assigned issue #31, will it fine with you if I work on this issue because I currently do not have any issue to work on.

**Comment by fenu28** [comment]
@dishantvyas15  As you have been assigned issue #31 , will it be fine with you if I work on this issue because I currently do not have any issue to work on.

**Comment by dishantvyas15** [comment]
@fenu28 If this gets assigned to you, then you may surely proceed.

**Comment by fenu28** [comment]
@HemangNakarani Can I take up this issue?

**Comment by HemangNakarani** [comment]
Ok, as @dishantvyas15 working on another issue, I am assigning it to @fenu28

**Comment by HemangNakarani** [comment]
Any Updates ? @fenu28

**Comment by fenu28** [comment]
@HemangNakarani I am getting some bugs while implementing the logic. Sorry for the delay. I will try to solve it ASAP
