### ISSUE TITLE
OnBackPress Actions

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#35]
- [ ] When you BackPress from either of ```LayoutOneActivity``` or ```LayoutTwoActivity``` it should show Toast ***Press Back again to exit the app*** 
- [ ] If user has not presses back button in 2 Seconds then user should not exit from application
- [ ] For Other Activities BackPress should take user to the Parent Activity
![image](https://user-images.githubusercontent.com/45796208/95122502-3f04ac80-076e-11eb-9983-becc7a1e9e32.png)
- Refer StackOverFlow

**Comment by fenu28** [comment]
PR done

**Comment by HemangNakarani** [comment]
@fenu28 That's great, but do not do it again, if issue is not assigned to you.
