### ISSUE TITLE
Make Inherited Side Navigation Drawer For Two Activities

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#4]
We have two layouts for displaying coding contests, so make a drawer for both activities which is inherited from abstract base activity.

**Comment by HemangNakarani** [comment]
@sanchi0204 can you work on this issue?

**Comment by sanchi0204** [comment]
Okay, I can try. Can u pls elaborate a bit more to help me understand better

**Comment by HemangNakarani** [comment]
- You will have to create one abstract base activity, so that ```LayoutOneActivity```  and ```LayoutTwoActivity``` will extend this abstract base activity. Now all features of base activity will inherit in ```LayoutOneActivity``` and ```LayoutTwoActivity```. So if you make drawer in base activity then it would inherit in both the activities. This way you just need to write the drawer's code once, it will work for ```LayoutOneActivity```  as well as ```LayoutTwoActivity```

- You will need to search for things to make it. So do it, you can learn how some of OOPs concepts can be user in apps.

## References 
- [BaseAvtivity](https://github.com/HemangNakarani/Coder-s-Calendar/blob/master/app/src/main/java/com/noobsever/codingcontests/StartActivity.java)
- [Layout of BaseActivity](https://github.com/HemangNakarani/Coder-s-Calendar/blob/master/app/src/main/res/layout/activity_start1.xml)
- [LayoutOne/TwoAvtivity](https://github.com/HemangNakarani/Coder-s-Calendar/blob/master/app/src/main/java/com/noobsever/codingcontests/MainActivity.java)

**Good Luck !!!**

**Comment by sanchi0204** [comment]
> * You will have to create one abstract base activity, so that `LayoutOneActivity`  and `LayoutTwoActivity` will extend this abstract base activity. Now all features of base activity will inherit in `LayoutOneActivity` and `LayoutTwoActivity`. So if you make drawer in base activity then it would inherit in both the activities. This way you just need to write the drawer's code once, it will work for `LayoutOneActivity`  as well as `LayoutTwoActivity`
> * You will need to search for things to make it. So do it, you can learn how some of OOPs concepts can be user in apps.
> 
> ## References
> * [BaseAvtivity](https://github.com/HemangNakarani/Coder-s-Calendar/blob/master/app/src/main/java/com/noobsever/codingcontests/StartActivity.java)
> * [Layout of BaseActivity](https://github.com/HemangNakarani/Coder-s-Calendar/blob/master/app/src/main/res/layout/activity_start1.xml)
> * [LayoutOne/TwoAvtivity](https://github.com/HemangNakarani/Coder-s-Calendar/blob/master/app/src/main/java/com/noobsever/codingcontests/MainActivity.java)
> 
> **Good Luck !!!**

Okay thank you, I will work on this. Pls assign me the issue

**Comment by HemangNakarani** [comment]
@sanchi0204 Any Updates on it ?

**Comment by sanchi0204** [comment]
> @sanchi0204 Any Updates on it ?

I am working on it. Will make a PR soon

**Comment by sanchi0204** [comment]
@HemangNakarani pls review the PR

**Comment by HemangNakarani** [comment]
> @HemangNakarani pls review the PR

Done, Headout to this https://github.com/prit29/Coders-Calendar/pull/42#pullrequestreview-504754874
