### ISSUE TITLE
Card Design of Displaying Coding Contest

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#5]
- [x] Make Card Layout Using Material Components

**Comment by sanchi0204** [comment]
I would like to work on this for SLoP

**Comment by HemangNakarani** [comment]
@sanchi0204 Sure, You just need to make Card Layout of the contest. I have made the POJO class of the contest. According to it you can proceed.

See this, you don't need to make exactly the same as this, but just it should contain these fields
[https://cdn.discordapp.com/attachments/755464380925345854/760958392704696351/IMG-20200923-WA0000.jpg](url)

**Comment by sanchi0204** [comment]
> @sanchi0204 Sure, You just need to make Card Layout of the contest. I have made the POJO class of the contest. According to it you can proceed.
> 
> See this, you don't need to make exactly the same as this, but just it should contain these fields
> [https://cdn.discordapp.com/attachments/755464380925345854/760958392704696351/IMG-20200923-WA0000.jpg](url)

I am not able to access the given link

**Comment by HemangNakarani** [comment]
@sanchi0204 Just copy link and paste it in another tab

**Comment by sanchi0204** [comment]
Pls review the PR
