### ISSUE TITLE
Make Api-Call

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#54]
- [ ] Make ApiClient using Retrofit2
- [ ] Using ```okhttp3``` log the apicall details
- [ ] Make interface to call Api
- [ ] You'll also need the data model to catch the response
- [ ] Make Dummy Button in LayoutOneActivity - it should call API, and Logs should be printed in Logcat.
- Contact me for Api link
- [Reference](https://www.journaldev.com/13639/retrofit-android-example-tutorial)

**Comment by sanchi0204** [comment]
I would like to try this. Can you guide me through pls @HemangNakarani ?

**Comment by HemangNakarani** [comment]
Sure, Go ahead !

As you are working on this issue, I will wait for someone to take up the previous issue that I have assigned to you, If no one will be there then you can go ahead with it after completing work of this issue.

**Comment by HemangNakarani** [comment]
@sanchi0204 Any updates ?

**Comment by sanchi0204** [comment]
sorry. I am busy with my mid sems. Will make a PR soon

**Comment by HemangNakarani** [comment]
Ohk, No worries. You can start working on the project after exams. Good Luck. 👍

**Comment by sanchi0204** [comment]
@HemangNakarani I am completely clueless about this. Can you guide me a bit?

**Comment by HemangNakarani** [comment]
> @HemangNakarani I am completely clueless about this. Can you guide me a bit?

Yes Sure, I have already given API URL in Gitter group. Using that URL you will have to fetch data in our app. For that, you will have to use Retrofit. You will have to create a class to catch a data response from API. Just Call the API from LayoutOneActivity. You don't need to show data anywhere. Just log response data using HTTP Logging Interceptor. Later we will do API call using async process, If you can do it now it would be good.

Refer [this](https://www.journaldev.com/13639/retrofit-android-example-tutorial) article.

@sanchi0204 have you got it ? or should I explain anything else ?

**Comment by HemangNakarani** [comment]
@sanchi0204 any updates?
