### ISSUE TITLE
Make RecyclerView in All Fragments

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#55]
- [ ] You will need to write code for RecyclerViewAdapter 
- [ ] Use [this](https://github.com/prit29/Coders-Calendar/blob/master/app/src/main/res/layout/card_design.xml) as itemView which is already there in our project
- [ ] Show Stored Data in the respective tab according to platform

**Comment by prit29** [comment]
Half the work is done 😃
