### ISSUE TITLE
Implementing Room Database

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#56]
- [ ] Implement Database for ```ContestObject``` model
- [ ] You will have to implement functions for add object, retrieve all object list, query database by ```title```
- [ ] We'll be using RoomDatabase and Dao for this
- Learn About Querying SQLite Database
- Learn About MVVM architecture
- Use [this] for debugging database
- [Reference](https://www.youtube.com/playlist?list=PLrnPJCHvNZuDihTpkRs6SpZhqgBqPU118)

Feel Free to reach out to any of us

**Comment by ashishpatel16** [comment]
Can I work on this issue?

**Comment by HemangNakarani** [comment]
Yes, Sure !!
