### ISSUE TITLE
Checking Internet Connection

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#57]
- [ ] Add function to check if our app has an internet connection or not.
- [ ] Use this function in Base Activity, If the app is disconnected from the internet then show snackbar and set internet connection flag accordingly in SharedPreferences.

**Comment by sanchi0204** [comment]
Can I work on this @HemangNakarani ?

**Comment by HemangNakarani** [comment]
Sure !!

**Comment by dishantvyas15** [comment]
@HemangNakarani I'd like to work on this issue.

**Comment by HemangNakarani** [comment]
#66,  closing...
