### ISSUE TITLE
Help Activity Layout

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#58]
- [ ] Make Static Layout of Help Activity.
- [ ] It should show FAQ type layout.
- [ ] Make it show/hide type layout, if we click on the question then answer should appear under question, if we click other question then previous answer under other question should be disappear.
- [ ] Use Material-UI

![image](https://user-images.githubusercontent.com/45796208/96352516-6b5ee800-10e1-11eb-91eb-0212929933e0.png)

**Comment by fenu28** [comment]
@HemangNakarani I want to work on this issue.

**Comment by HemangNakarani** [comment]
Sure !! Assigned 👍

**Comment by fenu28** [comment]
@HemangNakarani Do we have the questions ready for our app or I should put the above questions in image for now?

**Comment by HemangNakarani** [comment]
Not those questions specifically, bur keep some demo questions, So we can change it later, You will also need to write code for making recyclerView and Pojo class for Question-Answers.

So I'll increase points.

**Comment by fenu28** [comment]
Ok cool. What I will try to do is first create a layout for the question-answers for recyclerView view holder. Then I will create a POJO class named something like "Help" or anything and it will contain the question, answer String variables and related getter, setters. Then I will also create a custom adapter for our question-answer recyclerView to populate the views. What do you think about this?

**Comment by HemangNakarani** [comment]
Yes Exactly, And for showing items in recycler view, just statically define ArrayList of Que-Ans objects for now.

**Comment by fenu28** [comment]
I tried to implement this with the simple RecyclerView. But the problems here are:

1. To implement the expanding functionality, we have to implement onClick() on each view holder of recycler view manually which can degrade performance.

2. To collapse any expanded question when another question is selected, we need to check by iterating over all ArrayList questions whether they are expanded or not every time. This can also degrade performance.

Any suggestions??

**Comment by HemangNakarani** [comment]
Well,
 - Your point 2. `To collapse any expanded question when another question is selected, we need to check by iterating over all ArrayList questions whether they are expanded or not every time. This can also degrade performance` will not be the actual case. Just think a little bit about it.

- And you can define `onClickListner` in `onBindViewHolder`. It is the right place to call itemClickListner for recycler view item. So there will not be any load. Refer [this](https://stackoverflow.com/questions/24885223/why-doesnt-recyclerview-have-onitemclicklistener).

**Comment by HemangNakarani** [comment]
@fenu28 any progress in it?

**Comment by fenu28** [comment]
@HemangNakarani sorry for the delay. I have exchanged my old laptop for a new one so it's taking time # get so much data from Google Drive. And regarding this issue, only the "one at a time question" feature is to be implemented. Currently by my modification, more than one question answer can stay open.

**Comment by HemangNakarani** [comment]
give @fenu28 75 points
