### ISSUE TITLE
Make Settings Page Design

### ISSUE THREAD

**Issue by HemangNakarani** [prit29/Coders-Calendar#7]
Settings Page will include Choices of Coding Platforms, Choice for Time Format (12 hr /24 hr), 

- [ ] Make design in photoshop, Figma, or anything you like - SLoP-25
- [ ] Implementing Layout in Application - SLoP-75

**Comment by sanchi0204** [comment]
I would like to work on this as a part of SLoP

**Comment by sanchi0204** [comment]
I have made a PR for the previously assigned issue. Pls assign this

**Comment by sanchi0204** [comment]
pls review the PR
